# Site settings
name: Data submission
group: EMBL-EBI Web Development
email: noreply@ebi.ac.uk
domain: //ebiwd.github.io
baseurl: /Data-submissions-interface
permalink: pretty

# Add custom CSS / JS here
custom_css:
- "/Data-submissions-interface/static/app.css"
# - "{{site.baseurl}}/static/css/ANOTHER-CSS-COMPONENTS.css"
custom_js:
- "/Data-submissions-interface/static/app.js"
# - "{{site.baseurl}}/static/js/ANOTHER-CSS-COMPONENTS.js"
ga_code: 'UA-XXXXX-X'

# root repo for this project
repo:        "https://github.com/ebiwd/Data-submissions-interface"
source:      .
destination: ./_site
exclude:     [node_modules, .sass-cache, gulpfile.js, package.json, HOWTO.md]
#plugins:     ./_plugins
future:      false
lsi:         false
markdown:    kramdown
highlighter: rouge

# Allow redirects
# https://help.github.com/articles/redirects-on-github-pages/
# gems:
#   - jekyll-redirect-from
